# Generated by Django 4.1.7 on 2023-05-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academicos', '0002_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='id_alumno',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
